spring.application.name=ordermymeal
spring.datasource.url=jdbc:postgresql://localhost:5432/ordermymeal
spring.datasource.username=${db_user_name}
spring.datasource.password=${db_password}
spring.jpa.hibernate.ddl-auto=update
server.port=8081